### ISSUE TITLE
Spredit: Loading a New SPR File Shows Incorrect Sprite Number

### ISSUE THREAD

**Issue by 0xvividmirage** [econtrerasd/F256-GraphicToolkit#14]
If I had a animation that had 10 frames and loaded an animation that had 5 frames, the 5 frame animation will show the wrong message of which frame it is on. 

Suggestion: Loading a SPR file should reset the screen to the 1st frame of whatever SPR file is loaded.

**Comment by econtrerasd** [comment]
Fixed, When loading the sprite shown is always the 1st sprite
