### ISSUE TITLE
Spredit: Allow Deleting of Any Frame From an SPR Animation

### ISSUE THREAD

**Issue by 0xvividmirage** [econtrerasd/F256-GraphicToolkit#15]
I would like to delete the very first frame of my animation, but it seems there is no way to do this. Using the remove sprite icon button just deletes the last frame.

Suggestions:
- clicking delete deletes whichever frame is loaded in the view
- clicking delete button should prompt for which frame in the animation to delete. Then select using number key.

**Comment by econtrerasd** [comment]
Not easy at all to implement.. will have to think on how to do it.. different size sprites use different amount of memory, would need to move everything in memory when you delete a sprite in the middle..

**Comment by econtrerasd** [comment]
Not planned since it's not easy at all to implement.. since different size sprites use different amount of memory, would need to scan and move everything in memory when you delete a sprite in the middle...
