### ISSUE TITLE
Spredit: Wrap-around Sprite Frames

### ISSUE THREAD

**Issue by 0xvividmirage** [econtrerasd/F256-GraphicToolkit#16]
When previewing cyclic animations, it would be useful to be able to continuously press arrow-left/artow-right to progress the animation so that the last frame in either direction, returns to the first frame/ last frame.

**Comment by econtrerasd** [comment]
Mmm good idea!, pretty easy to do too!

**Comment by econtrerasd** [comment]
Implemented, wil publish tomorrow

**Comment by econtrerasd** [comment]
Implemented, will republish a maintenance release of V1.3 with this change
