### ISSUE TITLE
Spredit: Enhance spr2str.bas / Integrate Into Toolkit 

### ISSUE THREAD

**Issue by 0xvividmirage** [econtrerasd/F256-GraphicToolkit#17]
It seems right now spr2str.bas is for turning an SPR file into a SSPR file which is a strip version of the sprite file.

An enhancement could be to merge multiple SPR into one SSPR file.

Another enhancement would be that it can be loaded into the Graphics Toolkit to edit that merged SSPR file. 

As far as implementation I think I need to leave it up to you... I think it might be cool to make the SSPR be a farmat that still references each SPR that it is made of so that one could delete a SPR and it would skip over the missing/deleted SPR. It would also know that when you edit frame 11 in the SSPR it recalls that its from SPR #2 in the sequence.

Up to you as far as how far you want to take this.

**Comment by econtrerasd** [comment]
Integrated into the toolkit in version 1.3
