### ISSUE TITLE
Spredit: Merge SPR Files and Preview them as a Reference Image

### ISSUE THREAD

**Issue by 0xvividmirage** [econtrerasd/F256-GraphicToolkit#18]
**SPR as a Reference Image:**
... do you think it makes sense to load a particular SPR as a reference image that is separate from the buffer image? I find when doing these frames i need a reference image. would be good to just have this as a feature in the toolkit?...

**Merge an SPR Into Loaded Scene**
... im currently making each animation for each walk direction as a separate file -- robot-walk_n, robot-walk_s, etc.. so when M**** gets the final result, I was hoping id be able to give him each direction combined into one file called robot-walk, that includes all 4 directions. so they way this fits into a preview "window" would be there could be a "load SPR reference" button, which loads it in, lets say the upper right of the workspace. under the preview could be a "merge into scene" button, which takes the loaded SPR and appends it to the end of the currently loaded SPR.

without this feature, i was just going to give M**** a bunch of SSPRs and let him load them in whatever way he wants. My understanding from my game dev experience is that loading one strip that has everything in it for a particular sprite, is faster and more efficient...._

**Comment by econtrerasd** [comment]
Merge got implemented, the scene part was not..
