### ISSUE TITLE
Left and Right Keys for Previous Frame/ Next Frame

### ISSUE THREAD

**Issue by 0xvividmirage** [econtrerasd/F256-GraphicToolkit#2]
Would be nice to have a shortcut where pressing left or right keys goes forward or backward a frame for a sprite sequence animation test.

**Comment by econtrerasd** [comment]
Sounds good, I'll take a look!

**Comment by 0xvividmirage** [comment]
I see you've added this feature and given me the BAS file for it. Thanks!
