### ISSUE TITLE
Exit Should Return You To the Toolkit Menu

### ISSUE THREAD

**Issue by 0xvividmirage** [econtrerasd/F256-GraphicToolkit#5]
Choosing "Exit" in the UI should bring you back to the Toolkit Menu.

**Comment by econtrerasd** [comment]
Oh that is weird, indeed it should take you back to the menu!, what happens
when you exit?

**Comment by 0xvividmirage** [comment]
I just tested this and it does indeed work... Howver, yesterday I exit and it showed a screen that said, "thanks for using the the sprite editor" or something like that. Then it hung there. Could be an obscure bug. I'll close and see if I can reproduce this with steps later.
