### ISSUE TITLE
Grab Color Mouse Shortcut

### ISSUE THREAD

**Issue by 0xvividmirage** [econtrerasd/F256-GraphicToolkit#7]
If we support right-click, I think grabbing the color of a pixel using right click (while the draw tool is selected) is more natural.

**Comment by econtrerasd** [comment]
Right click indeed picks the color of a pixel already.., can you test it
and report?, using the space key also works for picking the color (if you
are using a joystick to draw it's covenient..)

**Comment by 0xvividmirage** [comment]
I wasn't aware of this. Thanks!
